---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.openshiftVirtualization.namespaceName }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.openshiftVirtualization.operatorGroupName }}
  namespace: {{ .Values.openshiftVirtualization.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - {{ .Values.openshiftVirtualization.namespaceName }}
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kubevirt-hyperconverged.openshift-cnv: ''
  name: {{ .Values.openshiftVirtualization.subscriptionName }}
  namespace: {{ .Values.openshiftVirtualization.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace