apiVersion: v1
kind: Secret
metadata:
  name: ansible-user-token
  namespace: '{{ .Values.aap.namespaceName }}'
  annotations:
    kubernetes.io/service-account.name: ansible-user
    argocd.argoproj.io/sync-wave: "3"
type: kubernetes.io/service-account-token