---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansible-user
  namespace: {{ .Values.aap.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ansible-user-admin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ansible-user
  namespace: {{ .Values.aap.namespaceName }}