- name: Wait for virtual machines to be ready
  hosts: "namespace_{{ my_namespace | default('workloads') | replace('-', '_') }}" #Ansible does not admit "-" in the host names, so it replaces it with "_", hence you need your playbook to be aware of it
  gather_facts: no
  
  tasks:

    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 300
